Fix network requests broken by zscaler
When running these tests on a laptop running ZScaler, these tests were
failing when performing network requests with:

    Error: apiRequestContext.get: unable to get local issuer certificate

Adding NODE_USE_SYSTEM_CA=1 to the .env file seems to fix this,
allowing node to trust ZScaler's man-in-the-middle interference.